### ISSUE TITLE
There is no pytorch model.

### ISSUE THREAD

**Issue by ai-Ilike** [Aoi-hosizora/FFDNet_pytorch#2]
你好！这个project的model有没有，能不能给一份我测试一下降噪效果？谢谢！

**Comment by Aoi-hosizora** [comment]
It is best for you to train the model by yourself. I have trained this model only a few epochs, so my pth model has a bad effect.

Here is my pth model's effect.

![noisy](https://user-images.githubusercontent.com/31433480/122148958-e30e2e00-ce8d-11eb-8beb-aa1fa91eb77d.png)

![ffdnet](https://user-images.githubusercontent.com/31433480/122148995-ef928680-ce8d-11eb-8fb0-4c99225fb80d.png)
